In [18]:
import pandas as pd

In [23]:
data = pd.read_csv('Data/spotify-data.csv')

In [26]:
data[data.duplicated()]

Empty DataFrame
Columns: [artist_name, track_name, track_id, popularity, year, genre, danceability, energy, key, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo, duration_ms, time_signature]
Index: []

In [24]:
#displaying first 5 rows of the whole dataset
data.head()

,artist_name,track_name,track_id,popularity,year,genre,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,Jason Mraz,I Won't Give Up,53QF56cjZA9RTuuMZDrSA6,68,2012,acoustic,0.483,0.303,4,-10.058,1,0.0429,0.6940,0.000000,0.1150,0.139,133.406,240166,3
1,Jason Mraz,93 Million Miles,1s8tP3jP4GZcyHDsjvw218,50,2012,acoustic,0.572,0.454,3,-10.286,1,0.0258,0.4770,0.000014,0.0974,0.515,140.182,216387,4
2,Joshua Hyslop,Do Not Let Me Go,7BRCa8MPiyuvr2VU3O9W0F,57,2012,acoustic,0.409,0.234,3,-13.711,1,0.0323,0.3380,0.000050,0.0895,0.145,139.832,158960,4
3,Boyce Avenue,Fast Car,63wsZUhUZLlh1OsyrZq7sz,58,2012,acoustic,0.392,0.251,10,-9.845,1,0.0363,0.8070,0.000000,0.0797,0.508,204.961,304293,4
4,Andrew Belle,Sky's Still Blue,6nXIYClvJAfi6ujLiKqEq8,54,2012,acoustic,0.430,0.791,6,-5.419,0,0.0302,0.0726,0.019300,0.1100,0.217,171.864,244320,4

In [38]:
genre_column = data['genre']
year_column = data['year']
artist_column = data['artist_name']

In [28]:
data.dropna(inplace=True)

In [29]:
data.isna().sum()

artist_name         0
track_name          0
track_id            0
popularity          0
year                0
genre               0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
duration_ms         0
time_signature      0
dtype: int64

In [31]:
data.head(2)

,artist_name,track_name,track_id,popularity,year,genre,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,Jason Mraz,I Won't Give Up,53QF56cjZA9RTuuMZDrSA6,68,2012,acoustic,0.483,0.303,4,-10.058,1,0.0429,0.694,0.000000,0.1150,0.139,133.406,240166,3
1,Jason Mraz,93 Million Miles,1s8tP3jP4GZcyHDsjvw218,50,2012,acoustic,0.572,0.454,3,-10.286,1,0.0258,0.477,0.000014,0.0974,0.515,140.182,216387,4

In [39]:
genre_data = pd.DataFrame(genre_column)
genre_data.head(2)

      genre
0  acoustic
1  acoustic

In [40]:
year_data = pd.DataFrame(year_column)
year_data.head(2)

   year
0  2012
1  2012

In [41]:
artist_data = pd.DataFrame(artist_column)
artist_data.head(2)

  artist_name
0  Jason Mraz
1  Jason Mraz

In [42]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1048559 entries, 0 to 1048574
Data columns (total 19 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   artist_name       1048559 non-null  object
 1   track_name        1048559 non-null  object
 2   track_id          1048559 non-null  object
 3   popularity        1048559 non-null  int64
 4   year              1048559 non-null  int64
 5   genre             1048559 non-null  object
 6   danceability      1048559 non-null  float64
 7   energy            1048559 non-null  float64
 8   key               1048559 non-null  int64
 9   loudness          1048559 non-null  float64
 10  mode              1048559 non-null  int64
 11  speechiness       1048559 non-null  float64
 12  acousticness      1048559 non-null  float64
 13  instrumentalness  1048559 non-null  float64
 14  liveness          1048559 non-null  float64
 15  valence           1048559 non-null  float64
 16  tempo             1048559 non-null  float64
 17  duration_ms       1048559 non-null  int64
 18  time_signature    1048559 non-null  int64
dtypes: float64(9), int64(6), object(4)
memory usage: 160.0+ MB

In [43]:
genre_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1048559 entries, 0 to 1048574
Data columns (total 1 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   genre   1048559 non-null  object
dtypes: object(1)
memory usage: 16.0+ MB

In [46]:
# Function to get decade from year
def get_decade(year):
    return str(year // 10 * 10) + 's'

# Apply function to create decade column
data['Decade'] = data['year'].apply(lambda year: get_decade(year))
data

,artist_name,track_name,track_id,popularity,year,genre,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature,Decade
0,Jason Mraz,I Won't Give Up,53QF56cjZA9RTuuMZDrSA6,68,2012,acoustic,0.483,0.303,4,-10.058,1,0.0429,0.69400,0.000000,0.1150,0.139,133.406,240166,3,2010s
1,Jason Mraz,93 Million Miles,1s8tP3jP4GZcyHDsjvw218,50,2012,acoustic,0.572,0.454,3,-10.286,1,0.0258,0.47700,0.000014,0.0974,0.515,140.182,216387,4,2010s
2,Joshua Hyslop,Do Not Let Me Go,7BRCa8MPiyuvr2VU3O9W0F,57,2012,acoustic,0.409,0.234,3,-13.711,1,0.0323,0.33800,0.000050,0.0895,0.145,139.832,158960,4,2010s
3,Boyce Avenue,Fast Car,63wsZUhUZLlh1OsyrZq7sz,58,2012,acoustic,0.392,0.251,10,-9.845,1,0.0363,0.80700,0.000000,0.0797,0.508,204.961,304293,4,2010s
4,Andrew Belle,Sky's Still Blue,6nXIYClvJAfi6ujLiKqEq8,54,2012,acoustic,0.430,0.791,6,-5.419,0,0.0302,0.07260,0.019300,0.1100,0.217,171.864,244320,4,2010s
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,Akkarai Subhalakshmi,Sravanam - Madhyamavathi - Adi (Live),1tpOChGX8v34yHVukGk8DG,0,2009,indian,0.419,0.748,2,-10.657,1,0.1940,0.67400,0.000022,0.0800,0.827,171.229,873027,4,2000s
1048571,Fossils,Guru,2NU6Ne7jNlunEkmat52m8W,13,2009,indian,0.576,0.787,2,-6.503,1,0.0459,0.00313,0.000621,0.3780,0.593,112.010,348475,4,2000s
1048572,Lalgudi Vijayalakshmi,Nidhichala,4w11WNonK6ZRGyWVWLWM8n,0,2009,indian,0.534,0.314,4,-13.593,1,0.0533,0.95100,0.762000,0.2890,0.490,138.522,1582187,4,2000s
1048573,Lalgudi Vijayalakshmi,Govardhana,1ypYdGD0dz8bRLUF9kdG1L,0,2009,indian,0.494,0.319,4,-14.487,0,0.0536,0.95800,0.784000,0.1010,0.398,150.335,801213,3,2000s
1048574,Lost Stories,False Promises [ASOT 389] **Tune Of The Week**...,57NPkCUhZxwoHmdXW4uVEU,0,2009,indian,0.557,0.900,11,-11.903,0,0.0583,0.01500,0.937000,0.2120,0.103,132.009,399972,4,2000s